### ISSUE TITLE
As a fan, I want to be able to edit my account preferences.

### ISSUE THREAD

**Issue by Tris10N** [wsu-cpts489-fa20/bp-music#6]
- [ ] Add/remove genres
- [ ] Add/remove venues
- [ ] Add/remove artists
- [ ] Change password
Needed so fan profiles can change their public and private account information

**Comment by maaaadijaaane** [comment]
Pushing this issue to Week 3, this issue couldn't be fully completed because I struggled to implement checkboxes, and get the selected values stored in MongoDB, I also ran into problems when merging with the master where the renderFanDialog was no longer visible when fan created account, which impeded my progress.
Image of testcafe running into error:
![image](https://user-images.githubusercontent.com/42153689/99852306-964fb800-2b35-11eb-9a1b-c009a11d0846.png)
